#!/usr/bin/env bash

C1_IP="172.16.1.2/24"
C1_GW="172.16.1.1"
C2_IP="172.16.1.3/24"
C2_GW="172.16.1.1"

INSTR=()
CMD=()
INSTR+=("Welcome to demo2. This will show you some simple commands to connect two
linux netnamespaces to VPP via an L2 bridge.")
CMD+=("")

INSTR+=("To show interfaces type:")
CMD+=("sudo vppctl show inter")

INSTR+=("Lets examine our workloads c1 and c2")
CMD+=("sudo ip netns exec c1 ip -o a")

INSTR+=("")
CMD+=("sudo ip netns exec c2 ip -o a")

INSTR+=("To add interfaces, we add the host-side of the veth link pair.")
CMD+=("ip link")

INSTR+=("The links we need to add are link1 and link2 so lets add them with")
CMD+=("sudo vppctl create host-interface name link1; sudo vppctl create host-interface name link2; sudo vppctl show inter")

INSTR+=("Change the links state to up")
CMD+=("sudo vppctl set interface state host-link1 up; sudo vppctl set interface state host-link2 up; sudo vppctl show inter")

INSTR+=("Add IP addresses for the other end of each veth link")
CMD+=("sudo vppctl set interface l2 bridge host-link1 1;  sudo vppctl set interface l2 bridge host-link2 1")

INSTR+=("You can also see the bridge-domain")
CMD+=("sudo vppctl show bridge-domain 1 detail")

INSTR+=("At long last you probably want to see some pings")
CMD+=("sudo ip netns exec c1 ping -c3 172.16.1.3")

INSTR+=("")
CMD+=("sudo ip netns exec c2 ping -c3 172.16.1.2")

INSTR+=("Thanks for doing demo1. To restart this demo and type these commands yourself \nvagrant ssh \nsudo /vagrant/netns.sh \ncat /vagrant/demo2.cmd")
CMD+=("")
